# Configuración Sentinel Hub
SENTINELHUB_CLIENT_ID = "358474d6-2326-4637-bf8e-30a709b2d6a6"
SENTINELHUB_CLIENT_SECRET = "b296cf70-c9d2-4e69-91f4-f7be80b99ed1" 
SENTINELHUB_INSTANCE_ID = "PLAK81593ed161694ad48faa8065411d2539"

# Configuración adicional (opcional)
USGS_USERNAME = "tu_usuario_usgs"
USGS_PASSWORD = "tu_password_usgs"
